// Sample products data for development
const products = [
  {
    name: 'Wireless Noise-Cancelling Headphones',
    description: 'Premium wireless headphones with active noise cancellation for immersive sound experience.',
    price: 249.99,
    imageUrl: 'https://images.pexels.com/photos/577769/pexels-photo-577769.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    category: 'Electronics',
    inStock: true,
    rating: 4.8,
    numReviews: 127,
  },
  {
    name: 'Smart Fitness Watch',
    description: 'Track your fitness goals with this sleek and feature-packed smart watch.',
    price: 199.99,
    imageUrl: 'https://images.pexels.com/photos/437037/pexels-photo-437037.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    category: 'Electronics',
    inStock: true,
    rating: 4.5,
    numReviews: 89,
  },
  {
    name: 'Premium Leather Backpack',
    description: 'Stylish and durable leather backpack perfect for work or travel.',
    price: 129.99,
    imageUrl: 'https://images.pexels.com/photos/934673/pexels-photo-934673.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    category: 'Accessories',
    inStock: true,
    rating: 4.7,
    numReviews: 65,
  },
  {
    name: 'Designer Sunglasses',
    description: 'Protect your eyes in style with these premium designer sunglasses.',
    price: 159.99,
    imageUrl: 'https://images.pexels.com/photos/701877/pexels-photo-701877.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    category: 'Accessories',
    inStock: true,
    rating: 4.6,
    numReviews: 42,
  },
  {
    name: 'Minimalist Analog Watch',
    description: 'Elegant minimalist watch with a premium leather strap.',
    price: 179.99,
    imageUrl: 'https://images.pexels.com/photos/1697214/pexels-photo-1697214.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    category: 'Accessories',
    inStock: true,
    rating: 4.9,
    numReviews: 28,
  },
  {
    name: 'Wireless Charging Pad',
    description: 'Fast wireless charging pad compatible with all Qi-enabled devices.',
    price: 39.99,
    imageUrl: 'https://images.pexels.com/photos/4526407/pexels-photo-4526407.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    category: 'Electronics',
    inStock: true,
    rating: 4.4,
    numReviews: 54,
  },
  {
    name: 'Premium Cotton T-Shirt',
    description: 'Ultra-soft premium cotton t-shirt with a modern fit.',
    price: 29.99,
    imageUrl: 'https://images.pexels.com/photos/1656684/pexels-photo-1656684.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    category: 'Clothing',
    inStock: true,
    rating: 4.3,
    numReviews: 76,
  },
  {
    name: 'Portable Bluetooth Speaker',
    description: 'Compact yet powerful Bluetooth speaker with 20 hours of battery life.',
    price: 89.99,
    imageUrl: 'https://images.pexels.com/photos/1279107/pexels-photo-1279107.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    category: 'Electronics',
    inStock: true,
    rating: 4.7,
    numReviews: 35,
  },
  {
    name: 'Designer Coffee Mug',
    description: 'Stylish and functional ceramic coffee mug with minimalist design.',
    price: 24.99,
    imageUrl: 'https://images.pexels.com/photos/1793035/pexels-photo-1793035.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    category: 'Home',
    inStock: true,
    rating: 4.5,
    numReviews: 42,
  },
  {
    name: 'Luxury Scented Candle',
    description: 'Hand-poured scented candle with natural ingredients and long burn time.',
    price: 34.99,
    imageUrl: 'https://images.pexels.com/photos/5644488/pexels-photo-5644488.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    category: 'Home',
    inStock: true,
    rating: 4.8,
    numReviews: 29,
  },
  {
    name: 'Organic Face Serum',
    description: 'Nourishing organic face serum with vitamin C for radiant skin.',
    price: 49.99,
    imageUrl: 'https://images.pexels.com/photos/6624862/pexels-photo-6624862.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    category: 'Beauty',
    inStock: true,
    rating: 4.9,
    numReviews: 37,
  },
  {
    name: 'Premium Denim Jeans',
    description: 'Classic denim jeans with a perfect fit and premium quality.',
    price: 79.99,
    imageUrl: 'https://images.pexels.com/photos/6311387/pexels-photo-6311387.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    category: 'Clothing',
    inStock: true,
    rating: 4.6,
    numReviews: 51,
  },
];

export default products;