name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure Docker to use Minikube's Docker daemon
      shell: powershell
      run: |
        # Get Minikube Docker env vars
        minikube docker-env | Out-String -Stream | ForEach-Object {
          if ($_ -match '^export (\w+)="?(.+?)"?$') {
            $varName = $Matches[1]
            $varValue = $Matches[2] -replace '\\', '\\'
            [Environment]::SetEnvironmentVariable($varName, $varValue)
            Write-Host "Set $varName = $varValue"
          }
        }
        
        # Verify Docker connection
        docker version

    - name: Build Docker image
      run: docker build -t mahnoorhafeez/project-mern:latest .

    - name: Push to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo $env:DOCKER_PASSWORD | docker login -u $env:DOCKER_USERNAME --password-stdin
        docker push mahnoorhafeez/project-mern:latest

    - name: Deploy to Minikube
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml