name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure Minikube and Docker
      shell: powershell
      run: |
        # Ensure Minikube is running (PowerShell compatible syntax)
        $minikubeStatus = minikube status
        if (-not ($minikubeStatus -like "*Running*")) {
          Write-Host "Starting Minikube..."
          minikube start
        }

        # Configure Docker to use Minikube's Docker daemon
        $envOutput = minikube -p minikube docker-env --shell powershell
        Invoke-Expression $envOutput

        # Verify Docker connection
        docker version
        Write-Host "Docker configured to use Minikube's daemon successfully"

    - name: Build Docker image
      shell: powershell
      run: |
        # Build using Minikube's Docker daemon
        docker build -t mahnoorhafeez/project-mern:latest .
        Write-Host "Docker image built successfully"

    - name: Push to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      shell: powershell
      run: |
        # Login and push
        echo $env:DOCKER_PASSWORD | docker login -u $env:DOCKER_USERNAME --password-stdin
        docker push mahnoorhafeez/project-mern:latest
        Write-Host "Image pushed to Docker Hub successfully"

    - name: Deploy to Minikube
      shell: powershell
      run: |
        # Apply Kubernetes manifests
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
        
        # Verify deployment
        kubectl get pods
        kubectl get services
        Write-Host "Application deployed to Minikube successfully"