name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure Docker to use Minikube's Docker daemon
      shell: powershell
      run: |
        # Start Minikube if not running
        minikube status || minikube start
        
        # Get and set Minikube Docker env vars
        $envVars = minikube -p minikube docker-env --shell powershell | Out-String
        Invoke-Expression $envVars
        
        # Verify Docker connection
        docker version

    - name: Build Docker image
      run: docker build -t mahnoorhafeez/project-mern:latest .

    - name: Push to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo $env:DOCKER_PASSWORD | docker login -u $env:DOCKER_USERNAME --password-stdin
        docker push mahnoorhafeez/project-mern:latest

    - name: Deploy to Minikube
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml