name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Start Minikube if not already running
      shell: powershell
      run: |
        minikube status
        if ($LASTEXITCODE -ne 0) {
          minikube start --driver=docker
        }

    - name: Configure Docker to use Minikube's daemon
      shell: powershell
      run: |
        $minikubeEnv = & minikube -p minikube docker-env --shell powershell
        if ($LASTEXITCODE -ne 0) {
          Write-Error "Failed to get Minikube Docker env"
          exit 1
        }
        $minikubeEnv | Out-File -FilePath .\minikube-docker-env.ps1 -Encoding utf8
        . .\minikube-docker-env.ps1
        docker info

    - name: Build Docker image in Minikube
      run: docker build -t mahnoorhafeez/project-mern:latest .

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker image
      run: docker push mahnoorhafeez/project-mern:latest

    - name: Deploy to Minikube
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
