name: Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    defaults:
      run:
        shell: powershell

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker to use Minikube’s Docker daemon
      run: |
        & minikube -p minikube docker-env --shell powershell | Invoke-Expression
        docker info

    - name: Build Frontend Docker image
      run: |
        cd frontend
        docker build -t myapp-frontend .

    - name: Build Backend Docker image
      run: |
        cd backend
        docker build -t myapp-backend .

    - name: Apply Kubernetes manifests
      run: |
        kubectl apply -f k8s/

    - name: Verify Deployment
      run: |
        kubectl get pods -A
        kubectl get services -A
