name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main  # Triggers only when code is pushed to the 'main' branch

jobs:
  build-deploy:
    runs-on: self-hosted  # Uses your Windows self-hosted runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Pulls your repo code into the runner

    - name: Use Minikube Docker daemon (PowerShell)
      run: |
        $EnvVars = & minikube -p minikube docker-env --shell powershell
        Invoke-Expression $EnvVars
      shell: powershell

    - name: Build Docker image
      run: |
        docker build -t mahnoorhafeez/project-mern:latest .

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker image
      run: docker push mahnoorhafeez/project-mern:latest

    - name: Deploy to Minikube
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
