name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Minikube Docker daemon
      shell: powershell
      run: |
        $envScript = & minikube -p minikube docker-env --shell powershell
        Write-Output "=== Minikube Docker Env ==="
        Write-Output $envScript
        Invoke-Expression $envScript

    - name: Build Docker image
      run: docker build -t mahnoorhafeez/project-mern:latest .

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker image
      run: docker push mahnoorhafeez/project-mern:latest

    - name: Deploy to Minikube
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
