name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # ✅ Get Minikube Docker env and export it to shell
    - name: Configure Docker to use Minikube daemon
      shell: powershell
      run: |
        $minikubeEnv = & minikube -p minikube docker-env --shell powershell
        echo "Minikube Docker Env:"
        echo $minikubeEnv

        # Write it to a temporary file
        $minikubeEnv | Out-File -FilePath minikube-docker-env.ps1 -Encoding utf8

    # ✅ Import the Docker env
    - name: Import Minikube Docker environment
      shell: powershell
      run: |
        . .\minikube-docker-env.ps1
        docker info  # This will confirm if Minikube's Docker is active

    # ✅ Build and push
    - name: Build Docker image inside Minikube
      run: docker build -t mahnoorhafeez/project-mern:latest .

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker image
      run: docker push mahnoorhafeez/project-mern:latest

    - name: Deploy to Minikube
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
