name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # ✅ Start Minikube first (required!)
    - name: Ensure Minikube is started
      shell: powershell
      run: |
        minikube status
        if ($LASTEXITCODE -ne 0) {
          minikube start --driver=docker
        }

    # ✅ Get Minikube Docker env and export it to shell
    - name: Configure Docker to use Minikube daemon
      shell: powershell
      run: |
        $minikubeEnv = & minikube -p minikube docker-env --shell powershell
        if ($minikubeEnv -eq "false") {
          Write-Error "Failed to get docker-env from Minikube"
          exit 1
        }
        echo "Minikube Docker Env:"
        echo $minikubeEnv

        # Save it to file
        $minikubeEnv | Out-File -FilePath minikube-docker-env.ps1 -Encoding utf8

    # ✅ Import the Docker env
    - name: Import Minikube Docker environment
      shell: powershell
      run: |
        . .\minikube-docker-env.ps1
        docker info

    - name: Build Docker image inside Minikube
      run: docker build -t mahnoorhafeez/project-mern:latest .

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker image
      run: docker push mahnoorhafeez/project-mern:latest

    - name: Deploy to Minikube
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
