name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set Docker environment manually for Minikube
      shell: powershell
      run: |
        $minikubePort = (minikube docker-env --shell powershell | Select-String "DOCKER_HOST" | ForEach-Object { $_.ToString().Split("=")[1].Trim('"').Split(":")[2] })
        $Env:DOCKER_TLS_VERIFY = "1"
        $Env:DOCKER_HOST = "tcp://127.0.0.1:$minikubePort"
        $Env:DOCKER_CERT_PATH = "C:\\Users\\HP\\.minikube\\certs"
        $Env:MINIKUBE_ACTIVE_DOCKERD = "minikube"

    - name: Build Docker image
      run: docker build -t mahnoorhafeez1/project-mern:latest .

    - name: Login to Docker Hub
      shell: bash
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker image
      run: docker push mahnoorhafeez1/project-mern:latest

    - name: Deploy to Minikube
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
        kubectl rollout restart deployment/backend-deployment
        kubectl rollout restart deployment/frontend-deployment
